#!/bin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").  
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#
# Copyright (c) 1994, by Sun Microsystems, Inc.
# All rights reserved.
#
#  @(#)mailp 3.8 00/10/05
#
#  mailp, newsp, filep, digestp, filofaxp, timemanp and timesysp
#  shell script de lancement de mp
#  (mail/news/file/digest/filofax/time-manager/time-system pretty printer)
#
#  Original:   Bruno Pillard      - October 1988.
#  Modified:   Rich Burridge      - June 1989.
#  Revisited:  Larry W. Virden    - August, September 1990.
#  Revisited:  Bruno Pillard      - September 1990.
#  Revisited:  David W. Sanderson - August 1991.

BIN=BINDIR

#  NOTE: Banner printing is disabled below, by the inclusion of the -h
#        switch to the lpr command. Most of the information that typically
#        appears on the banner sheet, is output in the mp banners. If you
#        wish to enable banner printing, then you should remove the -h switch.

PROG=mp
case $BIN in
/*)	PROG=$BIN/mp;;
esac
FLAGS=
STDIN=
LPARGS=

case $0 in
*mailp)	    ;;
*newsp)     FLAGS=-a  ;;
*digestp)   FLAGS=-d  ;;
*filep)	    FLAGS=-o; STDIN=-sstdin ;;
*filofaxp)  FLAGS=-ff ;;
*franklinp) FLAGS=-fp ;;
*timemanp)  FLAGS=-tm ;;
*timesysp)  FLAGS=-ts ;;
*)     	    echo Unknown pretty printer: $0
	    exit ;;
esac

# avoid using test - slow in v7 /bin/sh
# while	[ $# -gt 0 ]
for DUMMY in ${1+"$@"}
do
	case $1 in
	# flags to pass through to mp
	-F | -l)
		FLAGS="$FLAGS $1"
		shift
		;;
	-s)	FLAGS="$FLAGS -s\"$2\""
		STDIN=
		shift;shift
		;;
	-s*)	FLAGS="$FLAGS \"$1\""
		STDIN=
		shift
		;;

# Added provision got the X print server client too. Only -D option is used
# as -P is already used in this script.

	-D) FLAGS="$FLAGS $1 $2"
		LPDEST="$2"
		PRINTER="$LPDEST"
		shift;shift
		;;

	# allow both -d and -P to specify the printer name
	-d|-P)	LPDEST="$2"
		PRINTER="$LPDEST"
		shift;shift
		;;
	-d*|-P*)LPDEST=`echo "$1"|sed 's/^-.//'`
		PRINTER="$LPDEST"
		shift
		;;
        #-h)	LPARGS=-h
        -h)	
		if [ -d /usr/spool/lp ]
		then LPARGS="-o nobanner"
		else LPARGS=-h
		fi
		shift
		;;

	# explicit end of arguments
	--)	shift; break
		;;
	-*)	echo bad flag: $1
		shift
		;;
	# stop processing arguments with the first nondash argument
	*)	break
		;;
	esac
done

# If LPDEST or PRINTER is already set in the environment, and no -d or -P
# argument was given, then the appropriate variable will still affect the
# appropriate printing command.
if	[ -d /usr/spool/lp ]
then	PRINT_CMD="lp  ${LPDEST+-d${LPDEST}}   -t"
else	PRINT_CMD="lpr ${PRINTER+-P${PRINTER}} -J"
fi

# for v in '*' '#' PROG STDIN FLAGS PRINT_CMD LPARGS
# do	eval echo "\"$v\"" = \"\'\$$v\'\"
# done
# exit 0

case $# in
0)	eval $PROG $STDIN $FLAGS '|' ${PRINT_CMD}stdin $LPARGS
	;;
*)	for FILE
	do	eval $PROG $FLAGS $FILE '|' $PRINT_CMD$FILE $LPARGS
	done
	;;
esac

exit 0
