	How to build fsexam

1. Prerequisite

1.1 Compiler

Download and install SunStudio from
http://www.opensolaris.org/os/community/tools/sun_studio_tools/sun_studio_11_tools/ if have not installed SunStudio

1.2 CBE

Download and install CBE from http://dlc.sun.com/osol/jds/downloads/cbe/

2. Build

# ./autogen.sh --prefix=/path/to/your/prefix
# make
# make install
