#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright 2009 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
# Copyright 2011 Every City Ltd. All rights reserved.
#

include $(SRC)/Makefile.master

PROJECT		= ttf-sil-doulos
VER 		= $(PROJECT)-4.106
TARBALL		= $(PROJECT)_4.106.orig.tar.bz2
SOURCE_URL	= http://archive.ubuntu.com/ubuntu/pool/universe/t/$(PROJECT)/$(TARBALL)

FONTS = DoulosSILR.ttf

ID =	Doulos

DOCS =	README.$(ID).txt \
	FONTLOG.$(ID).txt

include ../Makefile.common

